//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public int Action_ID { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string ActionText { get; set; }
        public int UserID { get; set; }
        public string ComputerName { get; set; }
    
        public virtual User User { get; set; }
    }
}
