//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Operation = new HashSet<Operation>();
        }
    
        public int Device_ID { get; set; }
        public string FNum { get; set; }
        public string Name { get; set; }
        public string MetrData { get; set; }
        public int IDObject { get; set; }
        public string Param { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string NoteText { get; set; }
        public Nullable<bool> Removed { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<bool> PPR_Removed { get; set; }
        public Nullable<int> PPR_Period { get; set; }
    
        public virtual Object Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operation { get; set; }
    }
}
