//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetrBaseEntities : DbContext
    {
        public MetrBaseEntities()
            : base("name=MetrBaseEntities")
        {
        }

        private static MetrBaseEntities context;

        public static MetrBaseEntities GetContext()
        {
            if (context == null) context = new MetrBaseEntities();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actions> Actions { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<OperationDevice> OperationDevice { get; set; }
        public virtual DbSet<OperationStatus> OperationStatus { get; set; }
        public virtual DbSet<OperationType> OperationType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
