//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metr
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationDevice
    {
        public int ID_OperationDevice { get; set; }
        public int ID_Operation { get; set; }
        public int ID_Device { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
